# -*- coding: utf-8 -*-
"""Amazon_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2iNhySGUGEjh4lxPNM58hWGxgGOI6Wd
"""

import pandas as pd
data = pd.read_csv("amazon-purchases.csv")

#type(data["Order Date"][0]) #Date Column is a string
#Create a list with prime days inside it
prime_days = ["2022-07-12", "2022-07-13", "2021-06-21", "2021-06-22", "2020-10-13", "2020-10-14", "2019-07-15", "2019-07-16", "2018-07-17", "2018-07-18",]

prime_purchase = []
for i in data["Order Date"]:
    if i in prime_days:
        prime_purchase.append(1)
    else:
        prime_purchase.append(0)
data["Prime Purchase"] = prime_purchase

data["Prime Purchase"].value_counts()